### ISSUE TITLE
Add an auto-publish to pypi github action if CI passes and version has changed

### ISSUE THREAD

**Issue by creatorrr** [julep-ai/steadytext#17]
perhaps using the `setup-uv` github action. I have already added a secret called `PYPI_TOKEN`. Also added this repo and the github action name `publish-to-pypi.yml` as a trusted publisher to the pypi repo.

Example:

```
# publish-to-pypi.yml

name: "Publish"

on:
  release:
    types: ["published"]

jobs:
  run:
    name: "Build and publish release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python
        run: uv python install 3.12  # Or whatever version I want to use.

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish -t ${{ secrets.PYPI_TOKEN }}
```
